package youtube;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import youtube.classes.User;
import youtube.classes.Watchable;

/**
 * UserInfo class is for displaying and managing user information.
 * This class provides functionality for changing user icons,
 * viewing detailed information, and displaying current views.
 */
public class UserInfo extends javax.swing.JFrame {

    Youtube youtube;
    Simulation simulation;
    User currUser = null;
    DefaultListModel<String> listModel;
    
    /**
    * Creates a new instance of the UserInfo class.
    *
    * @param youtube The YouTube instance associated with this UserInfo
    */
    public UserInfo(Youtube youtube) {
        initComponents();
        setTitle("Users");
        this.youtube = youtube;
        this.simulation = youtube.getSimulation();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jLabel_thumnail.setVerticalAlignment(SwingConstants.CENTER); // or CENTER, BOTTOM
        jLabel_thumnail.setHorizontalAlignment(SwingConstants.CENTER); // or CENTER, RIGHT

        printUsers();
    }
    
    private void printUsers(){
        listModel = new DefaultListModel<>();

        for( User user : simulation.getUserList()){
            listModel.addElement(user.getUserName());
        }
        
        jList_printUsers.setModel(listModel);
    }
    
    public void setIconToUser(ImageIcon Icon){
        currUser.setThumnail(Icon);
        youtube.setThumnailToUser(currUser, Icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList_printUsers = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_detailedInformation = new javax.swing.JTextArea();
        jLabel_thumnail = new javax.swing.JLabel();
        jButton_changeIcon = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaCurrView = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList_printUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_printUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList_printUsersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList_printUsers);

        jTextArea_detailedInformation.setColumns(20);
        jTextArea_detailedInformation.setRows(5);
        jScrollPane2.setViewportView(jTextArea_detailedInformation);

        jButton_changeIcon.setText("CHANGE ICON");
        jButton_changeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_changeIconMousePressed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextAreaCurrView.setColumns(20);
        jTextAreaCurrView.setRows(5);
        jScrollPane3.setViewportView(jTextAreaCurrView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_thumnail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_changeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_thumnail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_changeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_printUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_printUsersMousePressed
    String selectedText = jList_printUsers.getSelectedValue();

    if (selectedText != null) {
        for( User user : simulation.getUserList()){
            String currUserName = user.getUserName();
            if (currUserName.equals(selectedText)) {
                jTextArea_detailedInformation.setText(user.informationToString());
                jLabel_thumnail.setIcon(user.getThumnail());
                Watchable currView = user.getCurrentView();
                if (currView != null){
                    String currViewInfo = user.printCurrView();
                    String basicInfo = user.getCurrentView().printInfoCurrView();
                    String durationTime = "";
                    if(basicInfo.contains("video")){
                    long differenceInSeconds = java.time.Duration.between(user.getStartWatching(), user.getLastTimeWatching()).getSeconds();
                    durationTime = String.format("The user has been watching the video for %d seconds",differenceInSeconds);
                    }
                    jTextAreaCurrView.setText(currViewInfo + durationTime);
                }
                else{
                    jTextAreaCurrView.setText("The user is choosing what to watch next\n");
                }
                currUser = user;
                break;
            }
        }
    }
    }//GEN-LAST:event_jList_printUsersMousePressed

    private void jButton_changeIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_changeIconMousePressed
        if( currUser != null){
            changeUserIcon newIcon = new changeUserIcon(this);
            newIcon.setVisible(true);
        }
    }//GEN-LAST:event_jButton_changeIconMousePressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultListModel<String> filteredModel = new DefaultListModel<>();

        String filterWord = jTextField1.getText();
        filterWord = filterWord.toLowerCase();
        
        for( int i =0 ; i< listModel.size(); i++){
            String word = listModel.elementAt(i);
            if( word.toLowerCase().contains(filterWord)){
                filteredModel.addElement(word);
            }
        }
        jList_printUsers.setModel(filteredModel);
    }//GEN-LAST:event_jTextField1KeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        final Youtube youtube = new Youtube(); 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfo(youtube).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_changeIcon;
    private javax.swing.JLabel jLabel_thumnail;
    private javax.swing.JList<String> jList_printUsers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaCurrView;
    private javax.swing.JTextArea jTextArea_detailedInformation;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
