package youtube;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import youtube.classes.User;

/**
 * The Youtube class represents the main application window for an application.
 * It provides a graphical user interface (GUI) for user interactions and serves as the entry point to the application.
 * The class manages the simulation, allowing users to create, display, and interact with users, channels, videos, and streams.
 * 
 * The GUI includes buttons for user-related actions such as creating users, viewing user information, channels, videos, and streams.
 * It also allows users to start, stop, continue, save, and load the simulation.
 * 
 * The simulation backend is handled by the {youtube.Simulation} class, which manages the logic and state of the application.
 * 
 * This class interacts with other GUI classes, such as {youtube.UserInfo}, {youtube.VideoInfo}, {youtube.StreamInfo},
 * and {youtube.ChannelInfo}, for displaying detailed information about users, videos, streams, and channels, respectively.
 * 
 * @see youtube.Simulation
 * @see youtube.UserInfo
 * @see youtube.VideoInfo
 * @see youtube.StreamInfo
 * @see youtube.ChannelInfo
 */
public class Youtube extends javax.swing.JFrame {

    /**
     * The simulation instance associated with the application.
     */
    Simulation simulation = null;
    
    /**
     * Creates a new Youtube instance, initializing the main application window.
     */
    public Youtube() {
        initComponents();
        setTitle("Youtube <3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        START = new javax.swing.JButton();
        jButton_UsersPrint = new javax.swing.JButton();
        jButton_ChannelPrint = new javax.swing.JButton();
        jButton_VideosPrint = new javax.swing.JButton();
        jButton_StreamsPrint = new javax.swing.JButton();
        STOP_CONT = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        LOAD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 153));

        START.setBackground(new java.awt.Color(167, 220, 241));
        START.setText("CREATION");
        START.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                STARTMousePressed(evt);
            }
        });

        jButton_UsersPrint.setText("Users");
        jButton_UsersPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_UsersPrintMousePressed(evt);
            }
        });

        jButton_ChannelPrint.setText("Channels");
        jButton_ChannelPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_ChannelPrintMousePressed(evt);
            }
        });

        jButton_VideosPrint.setText("Videos");
        jButton_VideosPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_VideosPrintMousePressed(evt);
            }
        });

        jButton_StreamsPrint.setText("Streams");
        jButton_StreamsPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_StreamsPrintMousePressed(evt);
            }
        });

        STOP_CONT.setBackground(new java.awt.Color(167, 220, 241));
        STOP_CONT.setText("STOP / CONTINUE");
        STOP_CONT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                STOP_CONTMousePressed(evt);
            }
        });

        SAVE.setBackground(new java.awt.Color(167, 220, 241));
        SAVE.setText("SAVE");
        SAVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SAVEMousePressed(evt);
            }
        });

        LOAD.setBackground(new java.awt.Color(167, 220, 241));
        LOAD.setText("LOAD");
        LOAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LOADMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_StreamsPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton_VideosPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton_ChannelPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_UsersPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(START, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(STOP_CONT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LOAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_UsersPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(START, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ChannelPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(STOP_CONT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_VideosPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_StreamsPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOAD, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void STARTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STARTMousePressed
        simulation = new Simulation();
    }//GEN-LAST:event_STARTMousePressed

    private void jButton_UsersPrintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_UsersPrintMousePressed
        UserInfo newWindow = new UserInfo(this);
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton_UsersPrintMousePressed

    private void jButton_VideosPrintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_VideosPrintMousePressed
        VideoInfo newWindow = new VideoInfo(this);

        newWindow.setVisible(true);    }//GEN-LAST:event_jButton_VideosPrintMousePressed

    private void jButton_StreamsPrintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_StreamsPrintMousePressed
        StreamInfo newWindow = new StreamInfo(this);
        newWindow.setVisible(true);  
    }//GEN-LAST:event_jButton_StreamsPrintMousePressed

    private void jButton_ChannelPrintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ChannelPrintMousePressed
        ChannelInfo newWindow = new ChannelInfo(this);
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton_ChannelPrintMousePressed

    private void STOP_CONTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOP_CONTMousePressed
        boolean value = simulation.getStopValue();
        if (value == false){
            simulation.stopThreads();
            STOP_CONT.setBackground(new Color(138,185,138));

        } else{
            simulation.restartThreads();
            STOP_CONT.setBackground(new Color(167,220,241));
        }
    }//GEN-LAST:event_STOP_CONTMousePressed

    private void SAVEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMousePressed
        simulation.stopThreads();
        simulation.saveSimulation("simulation.ser");
    }//GEN-LAST:event_SAVEMousePressed

    private void LOADMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOADMousePressed
        if (simulation == null){
            simulation = new Simulation();
        }
        simulation.stopThreads();
        try {
            simulation.loadSimulation("simulation.ser");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Youtube.class.getName()).log(Level.SEVERE, null, ex);
        }
        simulation.restartThreads();
    }//GEN-LAST:event_LOADMousePressed

    public Simulation getSimulation(){
        return this.simulation;
    }
    
    public void setThumnailToUser(User currUser, ImageIcon newIcon){
        String currUserUsername = currUser.getUserName();
        for( User user: simulation.getUserList() ){
           String UserUsername = user.getUserName();
           if (currUserUsername.equals(UserUsername)){
               user.setThumnail(newIcon);
           }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Youtube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Youtube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Youtube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Youtube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Youtube().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOAD;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton START;
    private javax.swing.JButton STOP_CONT;
    private javax.swing.JButton jButton_ChannelPrint;
    private javax.swing.JButton jButton_StreamsPrint;
    private javax.swing.JButton jButton_UsersPrint;
    private javax.swing.JButton jButton_VideosPrint;
    // End of variables declaration//GEN-END:variables
}
